### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by Tjone150** [Dr-Dreams/EasyApplyBot#1]
Hey currently when I use the application it will still apply to blacklisted companies and titles not sure why

**Comment by Dr-Dreams** [comment]
I have fixed this issue.

**Comment by Tjone150** [comment]
![Picture1](https://user-images.githubusercontent.com/101604749/236622585-e38c0ae9-81bf-400e-84af-cfcdaef760c8.png)
![Picture2](https://user-images.githubusercontent.com/101604749/236622591-b2cae883-6ffa-455f-abdf-6954070b60f2.png)
Even after implementing the changes the issue still persist for me if need be I can show you other parts of what I have input but I do believe that everything is in the format that was specified in the ReadMe.

**Comment by Dr-Dreams** [comment]
It is working very well. 

Try this method.
remove __pycache__
then start the application again

You can also use the titleblacklist and poster blacklist to blacklist that type of job.

**Comment by Dr-Dreams** [comment]
after editing the .yml please format it by using some extension. In VSCode you can do it by __Prettier code format__ extension.
